apiVersion: v1
kind: Service
metadata:
  name: lembretes-service
spec:
  #porta externa, acessivel fora do cluster
  type: NodePort
  selector:
    app: lembretes
  ports:
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000